# Generated by Django 4.0.5 on 2022-06-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(default='N/A', max_length=255)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('hometown', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Ghana', max_length=255)),
                ('f_name', models.CharField(blank=True, max_length=255)),
                ('m_name', models.CharField(blank=True, max_length=255)),
                ('request_info', models.TextField(blank=True)),
                ('remark', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('referral', models.CharField(blank=True, max_length=255)),
                ('is_client', models.BooleanField(blank=True, default=True)),
                ('is_student', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('full_name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msystem.person')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('duties', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, default='000', max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='msystem.person')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data-files')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datafiles', to='msystem.person')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=255)),
                ('date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='msystem.person')),
            ],
            options={
                'unique_together': {('person', 'date')},
            },
        ),
    ]
