# Generated by Django 4.0.5 on 2022-06-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
