# Generated by Django 4.0.5 on 2022-06-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
