# Generated by Django 4.0.5 on 2022-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0002_alter_person_is_employee_alter_person_is_rep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
