# Generated by Django 4.0.5 on 2022-06-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0002_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('full_name', 'phone')},
        ),
    ]
