# Generated by Django 4.0.5 on 2022-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0004_alter_person_country_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_rep',
        ),
    ]
