# Generated by Django 4.0.5 on 2023-06-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0004_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='person',
            name='request_info',
        ),
        migrations.RemoveField(
            model_name='person',
            name='solution',
        ),
    ]
