# Generated by Django 4.0.5 on 2022-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0005_remove_person_is_employee_remove_person_is_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
