# Generated by Django 4.0.5 on 2023-09-24 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msystem', '0005_remove_person_remark_remove_person_request_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_advanced_student',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('administrator', 'Administrator'), ('secretary', 'Secretary')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
