# Generated by Django 4.0.5 on 2023-09-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0006_person_is_advanced_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('interview', 'interview'), ('documentary', 'Documentary'), ('promotional', 'Promotional')], default='lecture', max_length=50)),
                ('language', models.CharField(default='english', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('archive', 'Archive'), ('published', 'Published')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('administrator', 'Administrator'), ('secretary', 'Secretary'), ('media_operations', 'Media Operations')], max_length=255),
        ),
    ]
