# Generated by Django 4.0.5 on 2022-06-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0006_alter_person_phone_alter_person_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='region',
            new_name='referral',
        ),
    ]
