# Generated by Django 4.0.5 on 2022-06-16 09:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0007_rename_region_person_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ph',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
