# Generated by Django 4.0.5 on 2022-06-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0008_person_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ph',
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data-files')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='datafiles', to='msystem.person')),
            ],
        ),
    ]
