# Generated by Django 4.0.5 on 2022-06-21 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0013_alter_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=255)),
                ('date', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='msystem.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
