# Generated by Django 4.0.5 on 2022-06-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0014_appointment_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duties',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('person', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('full_name', 'phone')},
        ),
    ]
