# Generated by Django 4.0.5 on 2022-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0015_employee_duties_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(blank=True, default='000', max_length=255),
        ),
    ]
