# Generated by Django 4.0.5 on 2022-06-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0016_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='duties',
        ),
    ]
