# Generated by Django 4.0.5 on 2022-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0017_remove_employee_duties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='duties',
            field=models.TextField(blank=True),
        ),
    ]
